version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb-test
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/mongodb/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor

volumes:
  mongodb_data:
